### ISSUE TITLE
left justifying in problem parts

### ISSUE THREAD

**Issue by cukierm** [parkmath/parkmath#29]
This is something I only noticed when editing the systems of equations lesson because it looks funny there.  The way our books are printed, when you have "part a" of a problem, even when the text goes onto a second line it lines up with the beginning of the text on the first line, not with the letter a.  However, in the new system, the second line begins at the same indentation as the problem part letter.

I could adjust this to look okay in the linear equations lesson, but maybe this should be a global change anyway.

**Comment by anandthakker** [comment]
ah - yeah, this should definitely be doable as a global style

**Comment by cukierm** [comment]
Oops, - I did notice something about this.  Not nearly as urgent as other stuff, though.  Sometimes problems have text outside of problem parts as well as problem parts.  When this happens, the letters a, b, etc are set to the left of this margin.  It looks more natural to me if the letters a, b, etc are vertically aligned with the left margin of the other text, so the problem parts look indented.  For example, contrast Book 5 Summary and Review, problems 23 and 24. Problem 23 has a bulleted list, and that looks right to me.  Problem 24 has problem parts, and that looks funny.

**Comment by anandthakker** [comment]
Okay, this should be fixed in 4b3d12aa4da20fa78e6562b2f67b8147e1398620

@cukierm I would not be surprised if this global change caused at least one small pagination issue somewhere, since the added indentation means that at least some problem parts will now spill over into taking up one more line than they were before.  A spot check with my admittedly tired eyes looks alright so far, though, heh.
